class ProductPage:

    add_to_card = "button-cart"
    img_prod = "img-responsive"
    big_img = "thumbnail"
    cost = "content > div:nth-child(1) > div.col-sm-4 > ul:nth-child(4) > li:nth-child(1) > h2"
    quantity = "input-quantity"
    basket = "cart-total"
    name_product = "input-name1"
    description = "#language1 > div:nth-child(2) > div > div > div.note-editing-area > div.note-editable.panel-body"
    tag_input = "input-meta-title1"
    model_aria = "#form-product > ul > li:nth-child(2) > a"
    model_input = "input-model"
    save = "#content > div.page-header > div > div > button > i"
    filter = "#button-filter"
    edit = "#form-product > div > table > tbody > tr:nth-child(1) > td:nth-child(8) > a"
    chekbox_select = "#form-product > div > table > tbody > tr:nth-child(1) > td:nth-child(1) > input[type="'checkbox'"]"
    delit = "#content > div.page-header > div > div > button.btn.btn-danger"
    success = "#content > div.container-fluid > div.alert.alert-success.alert-dismissible"